### PR TITLE
ignore other than animation/transition props

### PR DESCRIPTION
**Pull request by riophae**

### CODE REVIEW

**Comment by ai** [comment]
Thanks. Good fix. Can I apply and release it on weekend? I have conference tomorrow, sorry.

**Comment by ai** [comment]
But I promise, I will release fix in Saturday.

**Comment by riophae** [comment]
No need to rush :)

**Comment by riophae** [comment]
Slightly tweaked the test case to make it more straight. The old one `ease-test.png` is unable to reproduce the bug.

**Comment by riophae** [comment]
Hey, if you are not busy, really hope to see this released :)

**Comment by ai** [comment]
Oops 😅 I will try to close it today

**Comment by ai** [comment]
Released in 1.0.1

**Pull request merged**
